services:
  next-app:
    build: .
    container_name: nextjs-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: ["npm", "run", "dev"]