name: Deploy to AWS ECS (EC2)

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set Environment Variables
        run: |
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "ECR_REPOSITORY_URI=418272772550.dkr.ecr.us-east-1.amazonaws.com/nextjs-app" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "ECR_REPOSITORY_URI: $ECR_REPOSITORY_URI"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build and Push Docker Image
        run: |
          docker build -t nextjs-app .
          docker tag nextjs-app:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --desired-count 1 --force-new-deployment
